name: Publish To Npm

on: 
  push:
    branches: [ publish_npm ]
  pull_request:
    branches: [ publish_npm ]

# 开动作业
jobs:
  # 作业1 
  publish:
    runs-on: ubuntu-latest

    environment: npm
    name: "publish npm ing..."
    steps:
      - uses: actions/checkout@master
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 7.2.1
      - name: Install modules
        run: pnpm install
      - name: Build
        run: npm run build
      - name: "Publish to the npm registry"
        uses: primer/publish@3.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }} # 跟前面步骤中的 NPM_AUTH_TOKEN 保持一致
        with:
          default_branch: publish_npm
          # dir: 'dist'

